import { Station } from "@/types/station";
import { eidMissions } from "./missions";

export const eidQuizStations: Station[] = [
    {
        id: "quiz-001",

        type: "quiz",

        category: "islamic",

        title: "🌙 حكمة الأضحية",

        description: "تفكير بسيط حول معنى الأضحية",

        theme: "eid-al-adha",

        mood: "reflective",

        difficulty: 2,

        targetAgeGroup: "adult",

        question: "ما الأقرب لمعنى الأضحية؟",

        choices: ["الطاعة", "القوة", "الشهرة", "السفر"],

        answer: "الطاعة",

        hint: "فكر في قصة سيدنا إسماعيل عليه السلام",

        explanation: "الأضحية مرتبطة بالطاعة والثقة بالله.",

        reward: {
            stars: 1,
            canUnlockTreasure: true,
        },

        tinyMissionPool: eidMissions,
    },

    {
        id: "quiz-002",

        type: "quiz",

        category: "history",

        title: "🕋 رحلة هاجر",

        description: "محطة عن أم سيدنا إسماعيل",

        theme: "eid-al-adha",

        mood: "reflective",

        difficulty: 3,

        targetAgeGroup: "adult",

        question: "ما الصفة الأبرز في قصة السيدة هاجر؟",

        choices: ["الصبر", "الشجاعة", "الاعتماد على الله", "كل ما سبق"],

        answer: "كل ما سبق",

        hint: "فكر في المواقف الصعبة اللي مرت بيها هاجر في الصحراء",

        explanation:
            "بمجرد ما عرفت انه امر الله، صبرت على الابتلاء، اعتمدت على الله، وكانت شجاعة في مواجهة الصحراء.",

        reward: {
            stars: 2,
            canUnlockTreasure: true,
        },

        tinyMissionPool: eidMissions,
    },

    {
        id: "quiz-003",

        type: "quiz",

        category: "language",

        title: "📚 لغة ومعنى",

        description: "سؤال لغوي بسيط",

        theme: "eid-al-adha",

        mood: "cozy",

        difficulty: 2,

        targetAgeGroup: "kid",

        question: 'ما معنى كلمة "سكينة" ؟',

        choices: ["الهدوء", "السرعة", "القوة", "الحزن"],

        answer: "الهدوء",

        hint: " الشعور اللي بيجي مع رمضان والعبادة",

        explanation:
            "السكينة تعني الهدوء والطمأنينة اللي بيحس بيها الإنسان لما يكون قريب من الله.",

        reward: {
            stars: 1,
            canUnlockTreasure: false,
        },

        tinyMissionPool: eidMissions,
    },

    {
        id: "quiz-004",

        type: "quiz",

        category: "history",

        title: "🕋 مناسك الحج",

        description: "محطة فضول ومعرفة",

        theme: "eid-al-adha",

        mood: "mystery",

        difficulty: 3,

        targetAgeGroup: "adult",

        question: "ما أول مناسك الحج الكبرى يوم النحر؟",

        choices: ["رمي جمرة العقبة", "السعي", "طواف الوداع", "الحلق"],

        answer: "رمي جمرة العقبة",

        hint: "ابليس انت بتعيط ؟ ",

        explanation:
            "الجمرة الأولى هي رمي جمرة العقبة، وهي أول مناسك الحج الكبرى يوم النحر.",

        reward: {
            stars: 2,
            canUnlockTreasure: true,
        },

        tinyMissionPool: eidMissions,
    },

    // ========================================================================
    // القسم الأول: أسئلة أساسية وسهلة (Kids & Beginners) - Difficulty 1-2
    // الهدف: ترسيخ المعلومات الأساسية بطريقة ممتعة وبسيطة.
    //=======================================================================
    {
        id: "quiz-basic-kid-001",
        type: "quiz",
        category: "islamic",
        title: "🐑 فدية إسماعيل",
        description: "بداية قصة العيد",
        theme: "eid-al-adha",
        mood: "cozy",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "ماذا ذبح سيدنا إبراهيم بدلاً من ابنه إسماعيل؟",
        choices: ["جمل", "كبش", "بقرة", "دجاجة"],
        answer: "كبش",
        hint: "حيوان له صوف ويصوت مeee 🐑",
        explanation: "فدى الله إسماعيل بكبش عظيم، ومن هنا جاءت سنة الأضحية.",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },

    {
        id: "quiz-basic-kid-002",
        type: "quiz",
        category: "social",
        title: "👗 ملابس العيد",
        description: "سنن العيد الجميلة",
        theme: "eid-al-adha",
        mood: "playful",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "ماذا نلبس في يوم العيد؟",
        choices: ["ملابس النوم", "أجمل ثيابنا", "ملابس المدرسة", "لا شيء"],
        answer: "أجمل ثيابنا",
        hint: "ثياب نظيفة وجميلة ✨",
        explanation:
            "من السنة أن نتجميل ونلبس أحسن ملابسنا في العيد لإظهار الفرحة.",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },

    {
        id: "quiz-basic-adult-001",
        type: "quiz",
        category: "islamic",
        title: "🕌 صلاة العيد",
        description: "أين نصلي؟",
        theme: "eid-al-adha",
        mood: "social",
        difficulty: 1,
        targetAgeGroup: "adult",
        question: "أين يفضل أداء صلاة عيد الأضحى؟",
        choices: [
            "في البيت",
            "في المصلى الخارجي أو المسجد الكبير",
            "في السيارة",
            "في العمل",
        ],
        answer: "في المصلى الخارجي أو المسجد الكبير",
        hint: "مكان يتسع لجميع المسلمين 🕌",
        explanation:
            "السنة أن تصلى صلاة العيد في مصلى واسع أو مسجد كبير لاجتماع المسلمين.",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },

    {
        id: "quiz-basic-gen-001",
        type: "quiz",
        category: "fun",
        title: "🍉 فاكهة الصيف",
        description: "لغز بسيط",
        theme: "eid-al-adha",
        mood: "playful",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "فاكهة خضراء من الخارج وحمراء من الداخل، ما هي؟",
        choices: ["تفاح", "بطيخ", "موز", "برتقال"],
        answer: "بطيخ",
        hint: "بـ *** ـة (5 حروف)",
        explanation: "إنه البطيخ! فاكهة منعشة نحبها في الصيف والعيد.",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },

    // ========================================================================
    // القسم الثاني: أسئلة متوسطة وربط القيم (Intermediate) - Difficulty 2-3
    // الهدف: فهم المعاني والربط بين الأحداث والشخصيات.
    // ========================================================================


    {
        id: "quiz-mid-hajj-001",
        type: "quiz",
        category: "history",
        title: "🏃 سعي هاجر",
        description: "بين الصفا والمروة",
        theme: "eid-al-adha",
        mood: "mystery",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "من هي السيدة التي سعت بين الصفا والمروة؟",
        choices: ["سارة", "هاجر", "مريم", "آسية"],
        answer: "هاجر",
        hint: "أم سيدنا إسماعيل 👩‍👦",
        explanation:
            "سعي السيدة هاجر بحثاً عن الماء لابنها هو أصل لمنسك السعي في الحج.",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },

    {
        id: "quiz-mid-sunnah-001",
        type: "quiz",
        category: "social",
        title: "🤝 تهاني الصحابة",
        description: "كيف كانوا يحيون بعضهم؟",
        theme: "eid-al-adha",
        mood: "social",
        difficulty: 3,
        targetAgeGroup: "adult",
        question: "ما هو الدعاء الذي كان الصحابة يقوله بعضهم لبعض في العيد؟",
        choices: [
            "عيد سعيد",
            "كل عام وأنتم بخير",
            "تقبل الله منا ومنكم",
            "مبروك العيد",
        ],
        answer: "تقبل الله منا ومنكم",
        hint: "الدعاء بالقبول هو الأجمل 🤲",
        explanation:
            "كان الصحابة إذا التقوا يوم العيد يقول بعضهم لبعض: تقبل الله منا ومنكم.",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },

    {
        id: "quiz-mid-gen-001",
        type: "quiz",
        category: "language",
        title: "📚 ضد الكلمات",
        description: "تحدي لغوي بسيط",
        theme: "eid-al-adha",
        mood: "cozy",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "ما هو عكس كلمة 'فرح'؟",
        choices: ["سرور", "حزن", "نوم", "جوع"],
        answer: "حزن",
        hint: "شعور نحتاج فيه لاحتضان 🫂",
        explanation:
            "عكس الفرح هو الحزن. ونحن في العيد نحاول أن ندخل السرور على الجميع.",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },

    // ========================================================================
    // القسم الثالث: أسئلة صعبة جداً ومعقدة (Expert/Legend) - Difficulty 4
    // الهدف: تحدي المعلومات الدقيقة والفقه العميق والألغاز المعقدة.
    // ========================================================================

    {
        id: "quiz-hard-fiqh-001",
        type: "quiz",
        category: "islamic",
        title: "⚖️ حكم الأضحية",
        description: "دقة فقهية",
        theme: "eid-al-adha",
        mood: "reflective",
        difficulty: 4,
        targetAgeGroup: "adult",
        question: "ما هو الوقت الأقصى لذبح الأضحية عند جمهور العلماء؟",
        choices: [
            "حتى غروب شمس يوم العيد",
            "حتى غروب شمس آخر يوم من أيام التشريق (13 ذي الحجة)",
            "حتى نهاية شهر ذي الحجة",
            "قبل صلاة العيد بيوم",
        ],
        answer: "حتى غروب شمس آخر يوم من أيام التشريق (13 ذي الحجة)",
        hint: "أيام النحر أربعة أيام 🗓️",
        explanation:
            "وقت الأضحية يمتد لأربعة أيام: يوم العيد وثلاثة أيام بعده (أيام التشريق).",
        reward: { stars: 3, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },

    {
        id: "quiz-hard-history-001",
        type: "quiz",
        category: "history",
        title: "🕋 خطبة الوداع",
        description: "تاريخ دقيق",
        theme: "eid-al-adha",
        mood: "mystery",
        difficulty: 4,
        targetAgeGroup: "adult",
        question: "في أي يوم بالضبط ألقى النبي ﷺ خطبة الوداع؟",
        choices: [
            "يوم التروية",
            "يوم عرفة",
            "يوم النحر",
            "اليوم الثاني من التشريق",
        ],
        answer: "يوم عرفة",
        hint: "اليوم الذي يكمل فيه الدين 📜",
        explanation:
            "ألقى النبي خطبته العظيمة في يوم عرفة، ونزل فيه قول الله: 'اليوم أكملت لكم دينكم'.",
        reward: { stars: 3, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },

    {
        id: "quiz-hard-quran-001",
        type: "quiz",
        category: "wisdom",
        title: "⚛️ معادن القرآن",
        description: "إعجاز علمي دقيق",
        theme: "eid-al-adha",
        mood: "reflective",
        difficulty: 4,
        targetAgeGroup: "adult",
        question: "كم عدد المعادن التي ذُكرت باسمها صراحة في القرآن الكريم؟",
        choices: ["3 معادن", "6 معادن", "10 معادن", "12 معدناً"],
        answer: "6 معادن",
        hint: "الذهب، الفضة، الحديد، النحاس، الرصاص، القصدير 🔩",
        explanation:
            "ذكر القرآن 6 معادن صراحة: الذهب، الفضة، الحديد، النحاس، الرصاص، والقصدير.",
        reward: { stars: 3, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },

    {
        id: "quiz-hard-riddle-001",
        type: "quiz",
        category: "fun",
        title: "🧠 لغز العقل",
        description: "لغز منطقي معقد",
        theme: "eid-al-adha",
        mood: "mystery",
        difficulty: 4,
        targetAgeGroup: "adult",
        question: "ما هو الشيء الذي كلما أخذت منه كبر؟",
        choices: ["الحفرة", "العمر", "المال", "المعرفة"],
        answer: "الحفرة",
        hint: "تحفر في الأرض 🕳️",
        explanation:
            "الحفرة تكبر كلما أخذت (حفرت) منها تراباً أكثر. لغز يتطلب تفكيراً خارج الصندوق.",
        reward: { stars: 3, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },

    {
        id: "quiz-hard-prophet-001",
        type: "quiz",
        category: "history",
        title: "☀️ سنة النبي في العيد",
        description: "تفاصيل دقيقة من السيرة",
        theme: "eid-al-adha",
        mood: "cozy",
        difficulty: 4,
        targetAgeGroup: "adult",
        question: "كيف كان طريق النبي ﷺ في يوم العيد؟",
        choices: [
            "يذهب ويعود من نفس الطريق",
            "يذهب من طريق ويعود من طريق آخر",
            "يركب دابته فقط",
            "يمشي ماشياً فقط",
        ],
        answer: "يذهب من طريق ويعود من طريق آخر",
        hint: "ليظهر شعائر الإسلام في أكبر مساحة 🛣️",
        explanation:
            "كان النبي ﷺ يخالف الطريق ذهاباً وإياباً ليكثر من السلام وليظهر شعائر الإسلام في أنحاء المدينة.",
        reward: { stars: 3, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
/**
 * Kenzoo — Eid Al-Adha Quiz Pack v1
 * Rich replayable family-friendly quiz content
 */

 // ========================
    // محطات الأطفال (5-7 سنوات) - 50 سؤال (لهجة مصرية خفيفة)
    // ========================
    {
        id: "quiz-k-001",
        type: "quiz",
        category: "islamic",
        title: "🐳 صاحب الحوت",
        description: "حكاية نبي صبور",
        theme: "eid-al-adha",
        mood: "mystic",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "مين النبي اللي عاش جوه بطن الحوت وربنا حفظه؟",
        choices: ["يونس عليه السلام", "موسى عليه السلام", "نوح عليه السلام", "آدم عليه السلام"],
        answer: "يونس عليه السلام",
        hint: "🐳 حوت كبير",
        explanation: "سيدنا يونس فضل يسبح ربنا وهو جوه الحوت [1].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-002",
        type: "quiz",
        category: "riddles",
        title: "🦷 لغز السنان",
        description: "حاجة بنستعملها كل يوم",
        theme: "eid-al-adha",
        mood: "playful",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "إيه اللي ليه سنان كتير بس مش بيعض؟",
        choices: ["التمساح", "المشط", "المنشار", "الأسد"],
        answer: "المشط",
        hint: "💇 تسريح الشعر",
        explanation: "المشط بنسرح بيه شعرنا بس مش بيعض [2]، [3].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-003",
        type: "quiz",
        category: "islamic",
        title: "🚢 سفينة كبيرة",
        description: "معجزة في الموج",
        theme: "eid-al-adha",
        mood: "epic",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "مين النبي اللي ربنا أمره يبني سفينة ضخمة؟",
        choices: ["نوح عليه السلام", "إدريس عليه السلام", "صالح عليه السلام", "هود عليه السلام"],
        answer: "نوح عليه السلام",
        hint: "🌊 طوفان وموج",
        explanation: "سيدنا نوح بنى السفينة عشان ينقذ المؤمنين والحيوانات [4]، [5].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-004",
        type: "quiz",
        category: "nature",
        title: "☀️ شروق الشمس",
        description: "بص للسما",
        theme: "eid-al-adha",
        mood: "peaceful",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "الشمس الجميلة بتطلع كل يوم منين؟",
        choices: ["الشرق", "الغرب", "الشمال", "الجنوب"],
        answer: "الشرق",
        hint: "⬅️ جهة اليمين",
        explanation: "الشمس بتطلع من جهة الشرق وتنور الدنيا [6]، [7].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-005",
        type: "quiz",
        category: "islamic",
        title: "🕋 الكعبة المشرفة",
        description: "قبلة المسلمين",
        theme: "eid-al-adha",
        mood: "warm",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "إيه المكان اللي بنتوجه ليه واحنا بنصلي؟",
        choices: ["مكة (الكعبة)", "المدرسة", "الحديقة", "البيت"],
        answer: "مكة (الكعبة)",
        hint: "🕋 بيت ربنا",
        explanation: "الكعبة هي قبلة المسلمين وموجودة في مكة [8]، [9].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-006",
        type: "quiz",
        category: "animals",
        title: "🏃 أسرع واحد",
        description: "سباق الغابة",
        theme: "eid-al-adha",
        mood: "playful",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "مين أسرع حيوان بيمشي على الأرض؟",
        choices: ["الفهد", "الحصان", "الأرنب", "الفيل"],
        answer: "الفهد",
        hint: "🐆 سريع جداً",
        explanation: "الفهد هو أسرع حيوان بري في العالم [6]، [7].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-007",
        type: "quiz",
        category: "islamic",
        title: "🔥 برد وسلام",
        description: "قصة سيدنا إبراهيم",
        theme: "eid-al-adha",
        mood: "mystic",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "مين النبي اللي النار مأذتوش وكانت باردة عليه؟",
        choices: ["إبراهيم عليه السلام", "داود عليه السلام", "يحيى عليه السلام", "آدم عليه السلام"],
        answer: "إبراهيم عليه السلام",
        hint: "🔥 معجزة كبيرة",
        explanation: "ربنا أمر النار تكون برد وسلام على سيدنا إبراهيم [10]، [1].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-008",
        type: "quiz",
        category: "riddles",
        title: "🌧️ الغيمة الباكية",
        description: "فكر شوية",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "إيه اللي بيمشي من غير رجلين ويبكي من غير عينين؟",
        choices: ["السحاب", "السمكة", "العربية", "الوردة"],
        answer: "السحاب",
        hint: "☁️ في السما",
        explanation: "السحاب بيمشي مع الهوا وينزل مطر كأنه بيبكي [2]، [11].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-009",
        type: "quiz",
        category: "islamic",
        title: "🖐️ أركان الإسلام",
        description: "أساس ديننا",
        theme: "eid-al-adha",
        mood: "peaceful",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "أركان الإسلام كام واحد؟",
        choices: ["5 أركان", "3 أركان", "10 أركان", "ركن واحد"],
        answer: "5 أركان",
        hint: "🖐️ صوابع إيدك",
        explanation: "الإسلام مبني على 5 أركان أساسية [8]، [12].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-010",
        type: "quiz",
        category: "animals",
        title: "🦒 الزرافة الهادية",
        description: "معلومات عن الحيوانات",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "عارف الزرافة صوتها عامل إزاي؟",
        choices: ["ملهاش صوت", "بتنونو", "بتزأر", "بتهوهو"],
        answer: "ملهاش صوت",
        hint: "🔇 هدوء خالص",
        explanation: "الزرافة حيوان أبكم مش بيطلع صوت خالص [13]، [14].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-011",
        type: "quiz",
        category: "islamic",
        title: "🌿 أول إنسان",
        description: "بداية الحكاية",
        theme: "eid-al-adha",
        mood: "mystic",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "مين أول واحد ربنا خلقه وعاش على الأرض؟",
        choices: ["سيدنا آدم", "سيدنا محمد", "سيدنا عيسى", "سيدنا يوسف"],
        answer: "سيدنا آدم",
        hint: "🍎 أبو البشر",
        explanation: "سيدنا آدم هو أول إنسان خلقه ربنا [8]، [5].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-012",
        type: "quiz",
        category: "riddles",
        title: "🍳 لغز البيضة",
        description: "حاجة في المطبخ",
        theme: "eid-al-adha",
        mood: "playful",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "إيه الحاجة اللي لازم تتكسر قبل ما ناكلها؟",
        choices: ["البيضة", "البسكوت", "التفاحة", "الموزة"],
        answer: "البيضة",
        hint: "🐔 من الفرخة",
        explanation: "البيضة لازم تتكسر عشان نعرف نطبخها [15].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-013",
        type: "quiz",
        category: "islamic",
        title: "🐜 صوت النملة",
        description: "نبي بيفهم الحيوانات",
        theme: "eid-al-adha",
        mood: "mystic",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "مين النبي اللي سمع صوت النملة وهي بتتكلم؟",
        choices: ["سليمان عليه السلام", "صالح عليه السلام", "هود عليه السلام", "شعيب عليه السلام"],
        answer: "سليمان عليه السلام",
        hint: "👑 ملك عظيم",
        explanation: "سيدنا سليمان كان بيفهم لغة الطيور والحشرات والنمل [16].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-014",
        type: "quiz",
        category: "animals",
        title: "🐪 سفينة الصحراء",
        description: "صبر كبير",
        theme: "eid-al-adha",
        mood: "warm",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "مين الحيوان اللي بنسميه 'سفينة الصحراء'؟",
        choices: ["الجمل", "الحصان", "الحمار", "الغزالة"],
        answer: "الجمل",
        hint: "🐫 عنده سنام",
        explanation: "الجمل بيقدر يمشي في الرمل ويستحمل العطش [17].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-015",
        type: "quiz",
        category: "nature",
        title: "🍯 عسل نحل",
        description: "حاجة طعمها حلو",
        theme: "eid-al-adha",
        mood: "playful",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "مين الحشرة الشاطرة اللي بتعملنا العسل؟",
        choices: ["النحلة", "الدبانة", "الناموسة", "النملة"],
        answer: "النحلة",
        hint: "🐝 بتطير وتزن",
        explanation: "النحل بيمتص رحيق الورد ويحوله لعسل لذيذ [6]، [18].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-016",
        type: "quiz",
        category: "islamic",
        title: "💧 ماء زمزم",
        description: "بئر مبارك",
        theme: "eid-al-adha",
        mood: "warm",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "إيه اسم الميّة اللي طلعت تحت رجل سيدنا إسماعيل وهو صغير؟",
        choices: ["ماء زمزم", "ميّة النيل", "ميّة البحر", "ماء المطر"],
        answer: "ماء زمزم",
        hint: "🕋 في مكة",
        explanation: "ماء زمزم طلع بمعجزة عشان سيدنا إسماعيل وأمه يشربوا [19]، [20].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-017",
        type: "quiz",
        category: "riddles",
        title: "🛣️ لغز الطريق",
        description: "حاجة ثابتة",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "إيه اللي بيوديك المدرسة ويرجعك البيت من غير ما يتحرك؟",
        choices: ["الطريق", "العربية", "العجلة", "الطيارة"],
        answer: "الطريق",
        hint: "🛣️ بنمشي عليه",
        explanation: "الطريق بيفضل في مكانه واحنا اللي بنمشي عليه [13]، [21].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-018",
        type: "quiz",
        category: "nature",
        title: "🌈 ألوان قوس قزح",
        description: "بعد المطر",
        theme: "eid-al-adha",
        mood: "warm",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "قوس قزح الجميل فيه كام لون؟",
        choices: ["7 ألوان", "3 ألوان", "5 ألوان", "10 ألوان"],
        answer: "7 ألوان",
        hint: "🌈 ألوان كتير",
        explanation: "قوس قزح بيظهر بـ 7 ألوان روعة بعد المطر [22]، [23].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-019",
        type: "quiz",
        category: "islamic",
        title: "🕌 أحلى صلاة",
        description: "بكلم ربنا",
        theme: "eid-al-adha",
        mood: "peaceful",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "بنصلي كام مرة في اليوم؟",
        choices: ["5 مرات", "3 مرات", "10 مرات", "مرة واحدة"],
        answer: "5 مرات",
        hint: "🖐️ صوابع إيدك",
        explanation: "المسلم بيصلي 5 صلوات في اليوم عشان يفضل قريب من ربنا [24]، [8].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-020",
        type: "quiz",
        category: "animals",
        title: "🐘 الفيل الضخم",
        description: "حيوان كبير",
        theme: "eid-al-adha",
        mood: "playful",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "تعرف الفيل بيستخدم إيه عشان يحك ودنه؟",
        choices: ["زلومته", "رجله", "ديله", "الحجر"],
        answer: "زلومته",
        hint: "👃 مناخيره الطويلة",
        explanation: "الفيل بيستخدم زلومته الذكية في حاجات كتير [17]، [21].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-021",
        type: "quiz",
        category: "riddles",
        title: "👣 لغز الحفرة",
        description: "حاجة غريبة",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "إيه الحاجة اللي كل ما ناخد منها تكبر أكتر؟",
        choices: ["الحفرة", "الشنطة", "الحصالة", "العلبة"],
        answer: "الحفرة",
        hint: "🕳️ في الأرض",
        explanation: "الحفرة لما بنشيل منها تراب بتوسع وتكبر أكتر [25]، [11].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-022",
        type: "quiz",
        category: "islamic",
        title: "🕊️ أول مؤذن",
        description: "صوت الحق",
        theme: "eid-al-adha",
        mood: "epic",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "مين أول واحد أذن في الإسلام وصوته كان جميل؟",
        choices: ["بلال بن رباح", "أبو بكر", "عمر بن الخطاب", "علي بن أبي طالب"],
        answer: "بلال بن رباح",
        hint: "🗣️ صوت روعة",
        explanation: "سيدنا بلال هو أول مؤذن في الإسلام [26]، [27].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-023",
        type: "quiz",
        category: "nature",
        title: "🥛 لبن مفيد",
        description: "عشان نكبر",
        theme: "eid-al-adha",
        mood: "warm",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "بناخد اللبن المفيد من أنهي حيوان؟",
        choices: ["البقرة", "القطة", "الكلب", "الأرنب"],
        answer: "البقرة",
        hint: "🐄 بتقول مووو",
        explanation: "البقرة بتدينا لبن بيقوي عضمنا وسناننا [28].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-024",
        type: "quiz",
        category: "riddles",
        title: "🚪 الباب المفتوح",
        description: "فكر بالعقل",
        theme: "eid-al-adha",
        mood: "playful",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "إيه هو الباب اللي مستحيل نفتحه؟",
        choices: ["الباب المفتوح", "باب الخشب", "باب الحديد", "باب المدرسة"],
        answer: "الباب المفتوح",
        hint: "🔓 هو خلاص مفتوح",
        explanation: "الباب المفتوح أصلاً مش محتاج يتفتح [29]، [11].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-025",
        type: "quiz",
        category: "islamic",
        title: "🐫 ناقة صالح",
        description: "معجزة من الصخر",
        theme: "eid-al-adha",
        mood: "mystic",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "مين النبي اللي معجزته كانت ناقة خرجت من الصخرة؟",
        choices: ["سيدنا صالح", "سيدنا هود", "سيدنا شعيب", "سيدنا لوط"],
        answer: "سيدنا صالح",
        hint: "🐪 جمل ضخم",
        explanation: "ربنا طلع الناقة من وسط الصخرة كمعجزة لقوم سيدنا صالح [30]، [31].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-026",
        type: "quiz",
        category: "nature",
        title: "🍎 فاكهة الزبيب",
        description: "حاجة طعمها حلو",
        theme: "eid-al-adha",
        mood: "playful",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "إيه الفاكهة اللي لما بنجففها بتبقى زبيب؟",
        choices: ["العنب", "التفاح", "الموز", "البطيخ"],
        answer: "العنب",
        hint: "🍇 عنب صغير",
        explanation: "العنب هو اللي بيتحول لزبيب لما ينشف [32]، [33].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-027",
        type: "quiz",
        category: "islamic",
        title: "👶 أصغر صحابي",
        description: "شجاعة طفل",
        theme: "eid-al-adha",
        mood: "epic",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "مين أول واحد آمن بالنبي من الأطفال؟",
        choices: ["علي بن أبي طالب", "عمر بن الخطاب", "خالد بن الوليد", "زيد بن ثابت"],
        answer: "علي بن أبي طالب",
        hint: "🦁 بطل صغير",
        explanation: "سيدنا علي كان أول طفل يدخل الإسلام [34]، [35].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-028",
        type: "quiz",
        category: "riddles",
        title: "👂 لغز الصوت",
        description: "حاجة حوالينا",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "إيه اللي بيمشي من غير رجلين وبيدخل الودن؟",
        choices: ["الصوت", "النملة", "الميّة", "الهوا"],
        answer: "الصوت",
        hint: "📢 بنسمعه بس",
        explanation: "الصوت بيمشي في الهوا وبنسمعه بوداننا [36]، [37].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-029",
        type: "quiz",
        category: "nature",
        title: "🐟 السمك الشاطر",
        description: "بيعيش فين؟",
        theme: "eid-al-adha",
        mood: "playful",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "السمك الجميل بيعيش ويتنفس فين؟",
        choices: ["في الميّة", "في الهوا", "في الرمل", "فوق الشجر"],
        answer: "في الميّة",
        hint: "🌊 بحر ونهر",
        explanation: "السمك مكانه الطبيعي في الميّة ولو خرج يموت [28]، [38].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-030",
        type: "quiz",
        category: "islamic",
        title: "📖 كتاب ربنا",
        description: "كلام جميل",
        theme: "eid-al-adha",
        mood: "peaceful",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "إيه اسم الكتاب اللي نزل على سيدنا محمد؟",
        choices: ["القرآن الكريم", "الإنجيل", "التوراة", "الزبور"],
        answer: "القرآن الكريم",
        hint: "📗 بنقرأه دايماً",
        explanation: "القرآن هو كلام ربنا اللي نزل على نبينا محمد [8].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-031",
        type: "quiz",
        category: "riddles",
        title: "🖐️ لغز السمسم",
        description: "كلمة ممتعة",
        theme: "eid-al-adha",
        mood: "playful",
        difficulty: 3,
        targetAgeGroup: "kid",
        question: "كلمة لو أكلت نصها تموت ولو أكلتها كلها تستفيد؟",
        choices: ["سمسم", "تفاح", "موز", "تمر"],
        answer: "سمسم",
        hint: "🍪 فوق الكحك",
        explanation: "نص كلمة سمسم هي 'سم' [39]، [40].",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-032",
        type: "quiz",
        category: "nature",
        title: "🌙 القمر المنور",
        description: "في الليل",
        theme: "eid-al-adha",
        mood: "mystic",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "هو القمر منور من نفسه ولا بيعكس ضوء حاجة تانية؟",
        choices: ["بيعكس ضوء الشمس", "منور لوحده", "عنده لمبات", "بالكهرباء"],
        answer: "بيعكس ضوء الشمس",
        hint: "☀️ مراية كبيرة",
        explanation: "القمر بيعكس ضوء الشمس لينا فبيبان منور [41].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-033",
        type: "quiz",
        category: "islamic",
        title: "🐫 ناقة النبي",
        description: "صديقة الرسول",
        theme: "eid-al-adha",
        mood: "warm",
        difficulty: 3,
        targetAgeGroup: "kid",
        question: "عارف ناقة النبي محمد كان اسمها إيه؟",
        choices: ["القصواء", "البحث", "السريعة", "النور"],
        answer: "القصواء",
        hint: "🐫 جمل رائع",
        explanation: "القصواء هي الناقة اللي ركبها النبي في الهجرة [9].",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-034",
        type: "quiz",
        category: "riddles",
        title: "👓 لغز النضارة",
        description: "فكر في جسمك",
        theme: "eid-al-adha",
        mood: "playful",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "مين اللي بيلبس نضارة بس مش بيشوف؟",
        choices: ["الأنف", "العين", "الإيد", "الودن"],
        answer: "الأنف",
        hint: "👃 في وسط الوش",
        explanation: "النضارة بتسند على الأنف بس هو مش بيشوف [42].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-035",
        type: "quiz",
        category: "islamic",
        title: "💧 ماء الوضوء",
        description: "نظافة وعبادة",
        theme: "eid-al-adha",
        mood: "peaceful",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "بنعمل إيه بالميّة قبل ما نصلي؟",
        choices: ["نتوضأ", "نشرب", "نلعب", "ننام"],
        answer: "نتوضأ",
        hint: "🚿 غسل وشنا وإيدنا",
        explanation: "الوضوء هو اللي بيخلينا مستعدين للصلاة [8].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-036",
        type: "quiz",
        category: "animals",
        title: "🦁 الشبل الصغير",
        description: "أسماء الحيوانات",
        theme: "eid-al-adha",
        mood: "playful",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "صغير الأسد القوي اسمه إيه؟",
        choices: ["شبل", "كتكوت", "جرو", "مهر"],
        answer: "شبل",
        hint: "🦁 أسد صغنن",
        explanation: "ابن الأسد بنسميه شبل [43].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-037",
        type: "quiz",
        category: "islamic",
        title: "🕋 باني الكعبة",
        description: "قصة بناء بيت اهلل",
        theme: "eid-al-adha",
        mood: "warm",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "مين اللي بنى الكعبة مع ابنه إسماعيل؟",
        choices: ["إبراهيم عليه السلام", "موسى عليه السلام", "عيسى عليه السلام", "نوح عليه السلام"],
        answer: "إبراهيم عليه السلام",
        hint: "🕋 في مكة",
        explanation: "سيدنا إبراهيم وابنه إسماعيل هما اللي بنوا الكعبة [44].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-038",
        type: "quiz",
        category: "riddles",
        title: "🕯️ لغز الشمعة",
        description: "نور في الضلمة",
        theme: "eid-al-adha",
        mood: "peaceful",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "حاجة بتحرق نفسها عشان تنور للناس؟",
        choices: ["الشمعة", "اللمبة", "الشمس", "النار"],
        answer: "الشمعة",
        hint: "🔥 بتسيح بالراحة",
        explanation: "الشمعة بتخلص وهي بتدينا ضوء [43]، [45].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-039",
        type: "quiz",
        category: "nature",
        title: "🕸️ بيت العنكبوت",
        description: "بيت صغير أوي",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "إيه هو أضعف بيت موجود على الأرض؟",
        choices: ["بيت العنكبوت", "بيت الطوب", "بيت الخشب", "الخيمة"],
        answer: "بيت العنكبوت",
        hint: "🕷️ خيوط رفيعة",
        explanation: "بيت العنكبوت هو أضعف البيوت زي ما ربنا قال [46].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-040",
        type: "quiz",
        category: "islamic",
        title: "🐘 عام الفيل",
        description: "ميلاد النبي",
        theme: "eid-al-adha",
        mood: "epic",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "النبي محمد اتولد في عام اسمه إيه؟",
        choices: ["عام الفيل", "عام الفرح", "عام الحزن", "عام النصر"],
        answer: "عام الفيل",
        hint: "🐘 حيوان ضخم",
        explanation: "اتولد النبي صلى الله عليه وسلم في عام الفيل [47]، [9].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-041",
        type: "quiz",
        category: "animals",
        title: "🕷️ رجول العنكبوت",
        description: "عد صوابعك",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "العنكبوت الشاطر عنده كام رجل؟",
        choices: ["8 رجول", "4 رجول", "6 رجول", "2 بس"],
        answer: "8 رجول",
        hint: "🕷️ كتير أوي",
        explanation: "العنكبوت عنده 8 رجول بيتحرك بيها [18]، [7].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-042",
        type: "quiz",
        category: "islamic",
        title: "🕌 أول مسجد",
        description: "تاريخ البناء",
        theme: "eid-al-adha",
        mood: "warm",
        difficulty: 3,
        targetAgeGroup: "kid",
        question: "إيه أول مسجد بُني في الإسلام؟",
        choices: ["مسجد قباء", "المسجد النبوي", "المسجد الحرام", "المسجد الأقصى"],
        answer: "مسجد قباء",
        hint: "🕌 في المدينة",
        explanation: "بناه النبي صلى الله عليه وسلم لما وصل قباء [8]، [48].",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-043",
        type: "quiz",
        category: "riddles",
        title: "👣 لغز الظل",
        description: "ماشي معاك",
        theme: "eid-al-adha",
        mood: "playful",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "إيه اللي بيمشي في المطر بس مش بيتبل خالص؟",
        choices: ["الظل", "الإنسان", "العربية", "الكلب"],
        answer: "الظل",
        hint: "👤 خيالك",
        explanation: "ظلك بيمشي معاك بس هو مش جسم حقيقي يتبل [49].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-044",
        type: "quiz",
        category: "islamic",
        title: "🗣️ أول كلمة",
        description: "بداية القرآن",
        theme: "eid-al-adha",
        mood: "mystic",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "إيه أول كلمة نزلت من القرآن الكريم؟",
        choices: ["اقرأ", "اكتب", "اسمع", "تكلم"],
        answer: "اقرأ",
        hint: "📖 من القراءة",
        explanation: "جبريل قال للنبي 'اقرأ' في غار حراء [8].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-045",
        type: "quiz",
        category: "nature",
        title: "🍐 فاكهة القرآن",
        description: "أسماء السور",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "إيه السورة اللي اسمها على اسم فاكهة؟",
        choices: ["التين", "التفاح", "الموز", "البرتقال"],
        answer: "التين",
        hint: "🌳 سورة التين والـ...",
        explanation: "ربنا سمى سورة كاملة باسم التين [50]، [32].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-046",
        type: "quiz",
        category: "riddles",
        title: "🍽️ لغز الصحن",
        description: "وقت الأكل",
        theme: "eid-al-adha",
        mood: "playful",
        difficulty: 2,
        targetAgeGroup: "kid",
        question: "إيه الحاجة اللي بناكل منها بس مش بناكلها هي؟",
        choices: ["الصحن", "المعلقة", "الشوكة", "السكينة"],
        answer: "الصحن",
        hint: "🍽️ بنحط فيه الأكل",
        explanation: "الصحن بنحط فيه الأكل بس طبعاً مش بناكله [42].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-047",
        category: "islamic",
        title: "🐏 كبش العيد",
        type: "quiz",
        description: "قصة الأضحية",
        theme: "eid-al-adha",
        mood: "warm",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "ربنا فدى سيدنا إسماعيل بإيه عشان نضحي بيه في العيد؟",
        choices: ["كبش (خروف)", "جمل", "بقرة", "سمكة"],
        answer: "كبش (خروف)",
        hint: "🐑 بيقول مأأأأ",
        explanation: "ربنا نزل كبش كبير فداء لسيدنا إسماعيل [51].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-048",
        type: "quiz",
        category: "animals",
        title: "🐱 القطة الجميلة",
        description: "صوت الحيوان",
        theme: "eid-al-adha",
        mood: "playful",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "أنهي حيوان صوته اسمه مواء؟",
        choices: ["القطة", "الكلب", "الديك", "الحمار"],
        answer: "القطة",
        hint: "🐱 بتقول مياو",
        explanation: "صوت القطة هو المواء وهي حيوان أليف [28].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-049",
        type: "quiz",
        category: "islamic",
        title: "📜 الصادق الأمين",
        description: "لقب جميل",
        theme: "eid-al-adha",
        mood: "warm",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "مين النبي اللي كان لقبه الصادق الأمين؟",
        choices: ["محمد صلى الله عليه وسلم", "عيسى عليه السلام", "موسى عليه السلام", "يوسف عليه السلام"],
        answer: "محمد صلى الله عليه وسلم",
        hint: "🌹 نبينا الحبيب",
        explanation: "أهل مكة سموا النبي كدة لأنه مبيكدبش أبداً [52]، [48].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-k-050",
        type: "quiz",
        category: "riddles",
        title: "🖊️ لغز القلم",
        description: "في المدرسة",
        theme: "eid-al-adha",
        mood: "playful",
        difficulty: 1,
        targetAgeGroup: "kid",
        question: "إيه اللي بيكتب كتير بس مش بيعرف يقرأ؟",
        choices: ["القلم", "السبورة", "الكشكول", "الاستيكة"],
        answer: "القلم",
        hint: "✍️ بنمسكه بإيدنا",
        explanation: "القلم بنكتب بيه بس هو جماد مش بيقرأ [53]، [54].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },

    // ========================
    // محطات الكبار (Adult) - 50 سؤال (عربية سهلة دافئة)
    // ========================
    {
        id: "quiz-a-001",
        type: "quiz",
        category: "science",
        title: "🧠 طاقة الدماغ",
        description: "معلومة طبية مدهشة",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 2,
        targetAgeGroup: "adult",
        question: "كم يستهلك الدماغ البشري من إجمالي طاقة الجسم اليومية؟",
        choices: ["20%", "5%", "50%", "80%"],
        answer: "20%",
        hint: "💡 خُمس الطاقة",
        explanation: "رغم صغر حجمه، يستهلك الدماغ نحو 20% من طاقة الجسم [55]، [56].",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-002",
        type: "quiz",
        category: "islamic",
        title: "📜 ذي النورين",
        description: "ألقاب الصحابة الكرام",
        theme: "eid-al-adha",
        mood: "warm",
        difficulty: 1,
        targetAgeGroup: "adult",
        question: "من هو الصحابي الجليل الذي لُقب بـ 'ذي النورين'؟",
        choices: ["عثمان بن عفان", "أبو بكر الصديق", "عمر بن الخطاب", "علي بن أبي طالب"],
        answer: "عثمان بن عفان",
        hint: "💍 ثالث الخلفاء",
        explanation: "لقب بذلك لزواجه من ابنتي النبي رقية وأم كلثوم [57]، [27].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-003",
        type: "quiz",
        category: "geography",
        title: "🌍 أصغر دولة",
        description: "على خريطة العالم",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 1,
        targetAgeGroup: "adult",
        question: "ما هي أصغر دولة في العالم من حيث المساحة؟",
        choices: ["دولة الفاتيكان", "موناكو", "البحرين", "سان مارينو"],
        answer: "دولة الفاتيكان",
        hint: "🇮🇹 داخل روما",
        explanation: "تعتبر الفاتيكان هي الدولة الأصغر مساحة في العالم [53]، [58].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-004",
        type: "quiz",
        category: "psychology",
        title: "🤝 المعاملة بالمثل",
        description: "قواعد النفس البشرية",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 3,
        targetAgeGroup: "adult",
        question: "ماذا يُسمى الميل النفسي لرد الجميل لمن قدم لنا معروفاً؟",
        choices: ["قاعدة المعاملة بالمثل", "انحياز التوافر", "نصل أوكام", "مبدأ باريتو"],
        answer: "قاعدة المعاملة بالمثل",
        hint: "🎁 هات وخد",
        explanation: "هذا ميل طبيعي يجعلنا نريد موازنة العالقة مع الآخرين [59]، [60].",
        reward: { stars: 3, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-005",
        type: "quiz",
        category: "science",
        title: "🔬 جائزة نوبل",
        description: "منجزات علمية عربية",
        theme: "eid-al-adha",
        mood: "epic",
        difficulty: 2,
        targetAgeGroup: "adult",
        question: "من هو العالم العربي الحاصل على جائزة نوبل في الكيمياء؟",
        choices: ["أحمد زويل", "نجيب محفوظ", "مجدي يعقوب", "فاروق الباز"],
        answer: "أحمد زويل",
        hint: "🧪 الفيمتو ثانية",
        explanation: "حصل أحمد زويل على الجائزة لأبحاثه في الفيمتو ثانية [22]، [56].",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-006",
        type: "quiz",
        category: "history",
        title: "⚔️ القائد الفاتح",
        description: "فتح القسطنطينية",
        theme: "eid-al-adha",
        mood: "epic",
        difficulty: 2,
        targetAgeGroup: "adult",
        question: "من هو القائد الذي لقب بـ 'الفاتح' بعد فتح القسطنطينية؟",
        choices: ["محمد الثاني", "سليمان القانوني", "أرطغرل", "سليم الأول"],
        answer: "محمد الثاني",
        hint: "🇹🇷 محمد الفاتح",
        explanation: "السلطان محمد الفاتح هو من حقق هذا الفتح التاريخي [61]، [62].",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-007",
        type: "quiz",
        category: "islamic",
        title: "📜 جمع القرآن",
        description: "حفظ الوحي الإلهي",
        theme: "eid-al-adha",
        mood: "peaceful",
        difficulty: 3,
        targetAgeGroup: "adult",
        question: "من هو الصحابي الذي كلفه أبو بكر بجمع القرآن في مصحف واحد؟",
        choices: ["زيد بن ثابت", "عبد الله بن مسعود", "أبي بن كعب", "عثمان بن عفان"],
        answer: "زيد بن ثابت",
        hint: "🖋️ كاتب الوحي",
        explanation: "تم اختيار زيد بن ثابت لدقته وأمانته في تتبع آيات القرآن [27]، [63].",
        reward: { stars: 3, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-008",
        type: "quiz",
        category: "science",
        title: "🌌 الغاز الأكثر وفرة",
        description: "مكونات الغلاف الجوي",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 3,
        targetAgeGroup: "adult",
        question: "ما هو الغاز الأكثر انتشاراً في هواء الأرض بنسبة 78%؟",
        choices: ["النيتروجين", "الأكسجين", "ثاني أكسيد الكربون", "الهيدروجين"],
        answer: "النيتروجين",
        hint: "💨 ليس الأكسجين",
        explanation: "يشكل النيتروجين النسبة الكبرى من الهواء الجوي [64]، [56].",
        reward: { stars: 3, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-009",
        type: "quiz",
        category: "psychology",
        title: "📈 مبدأ باريتو",
        description: "قاعدة 80/20",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 3,
        targetAgeGroup: "adult",
        question: "ما الاسم العلمي للقاعدة التي تقول إن 80% من النتائج تأتي من 20% من الأسباب؟",
        choices: ["مبدأ باريتو", "قانون نيوتن", "نظرية فيثاغورس", "قانون ميلر"],
        answer: "مبدأ باريتو",
        hint: "📊 إدارة الوقت",
        explanation: "يستخدم مبدأ باريتو لتحسين التركيز والإنتاجية في الحياة [65].",
        reward: { stars: 3, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-010",
        type: "quiz",
        category: "islamic",
        title: "🛡️ معركة بدر",
        description: "يوم الفرقان",
        theme: "eid-al-adha",
        mood: "epic",
        difficulty: 2,
        targetAgeGroup: "adult",
        question: "في أي عام هجري وقعت معركة بدر الكبرى؟",
        choices: ["2 هـ", "1 هـ", "3 هـ", "5 هـ"],
        answer: "2 هـ",
        hint: "🗓️ السنة الثانية",
        explanation: "وقعت أول معركة كبرى في الإسلام في رمضان من السنة الثانية [66]، [67].",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-011",
        type: "quiz",
        category: "science",
        title: "🦷 عدد الأسنان",
        description: "جسم الإنسان البالغ",
        theme: "eid-al-adha",
        mood: "warm",
        difficulty: 1,
        targetAgeGroup: "adult",
        question: "كم عدد الأسنان لدى الإنسان البالغ؟",
        choices: ["32 سناً", "28 سناً", "20 سناً", "36 سناً"],
        answer: "32 سناً",
        hint: "🦷 كاملة بالضروس",
        explanation: "يمتلك الإنسان البالغ عادة 32 سناً تشمل ضروس العقل [68]، [7].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-012",
        type: "quiz",
        category: "history",
        title: "📜 حجر رشيد",
        description: "فك رموز الماضي",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 3,
        targetAgeGroup: "adult",
        question: "ما هي اللغة التي ساعد 'حجر رشيد' في فك رموزها؟",
        choices: ["الهيروغليفية", "اللاتينية", "السومرية", "اليونانية"],
        answer: "الهيروغليفية",
        hint: "🇪🇬 قدماء المصريين",
        explanation: "بفضل حجر رشيد، استطاع العلماء فهم كتابات المصريين القدماء [69].",
        reward: { stars: 3, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-013",
        type: "quiz",
        category: "islamic",
        title: "🛡️ أمين الأمة",
        description: "ألقاب الصحابة",
        theme: "eid-al-adha",
        mood: "warm",
        difficulty: 3,
        targetAgeGroup: "adult",
        question: "من هو الصحابي الذي لقبه النبي بـ 'أمين هذه الأمة'؟",
        choices: ["أبو عبيدة بن الجراح", "أبو بكر الصديق", "عمر بن الخطاب", "سعد بن معاذ"],
        answer: "أبو عبيدة بن الجراح",
        hint: "🛡️ فاتح الشام",
        explanation: "قال النبي: 'لكل أمة أمين، وأمين هذه الأمة أبو عبيدة' [27]، [70].",
        reward: { stars: 3, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-014",
        type: "quiz",
        category: "geography",
        title: "🏞️ أطول نهر",
        description: "شريان الحياة",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 1,
        targetAgeGroup: "adult",
        question: "ما هو أطول نهر في العالم؟",
        choices: ["نهر النيل", "نهر الأمازون", "نهر المسيسيبي", "نهر الدانوب"],
        answer: "نهر النيل",
        hint: "🇪🇬 في مصر والسودان",
        explanation: "يعتبر نهر النيل هو الأطول عالمياً ويمر عبر عدة دول أفريقية [53]، [71].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-015",
        type: "quiz",
        category: "science",
        title: "💓 لغز القلوب",
        description: "كائنات بحرية غريبة",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 2,
        targetAgeGroup: "adult",
        question: "أي حيوان يمتلك قلباً يقع في رأسه؟",
        choices: ["الجمبري (الروبيان)", "الأخطبوط", "الحوت", "القرش"],
        answer: "الجمبري (الروبيان)",
        hint: "🦐 قشريات",
        explanation: "من الحقائق العلمية الغريبة أن قلب الجمبري يقع في الرأس [72]، [7].",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-016",
        type: "quiz",
        category: "history",
        title: "⌛ الحرب الأقصر",
        description: "زمن قياسي",
        theme: "eid-al-adha",
        mood: "epic",
        difficulty: 4,
        targetAgeGroup: "adult",
        question: "كم استمرت أقصر حرب في التاريخ (بين إنجلترا وزنجبار)؟",
        choices: ["40 دقيقة تقريباً", "يوم واحد", "أسبوع واحد", "ساعة واحدة"],
        answer: "40 دقيقة تقريباً",
        hint: "⏱️ أقل من ساعة",
        explanation: "انتهت هذه الحرب في زمن يتراوح بين 38 إلى 45 دقيقة فقط [73]، [74].",
        reward: { stars: 4, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-017",
        type: "quiz",
        category: "islamic",
        title: "📜 صلح الحديبية",
        description: "حكمة سياسية",
        theme: "eid-al-adha",
        mood: "peaceful",
        difficulty: 3,
        targetAgeGroup: "adult",
        question: "من هو كاتب صلح الحديبية الذي رفض محو صفة 'رسول الله' لشدة حبه للنبي؟",
        choices: ["علي بن أبي طالب", "عمر بن الخطاب", "عثمان بن عفان", "زيد بن ثابت"],
        answer: "علي بن أبي طالب",
        hint: "🖋️ كاتب الصلح",
        explanation: "أصر علي بن أبي طالب على كتابة 'محمد رسول الله' في العقد [75].",
        reward: { stars: 3, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-018",
        type: "quiz",
        category: "science",
        title: "⚡ مخترع المصباح",
        description: "عالم التنوير",
        theme: "eid-al-adha",
        mood: "warm",
        difficulty: 1,
        targetAgeGroup: "adult",
        question: "من هو العالم الذي اخترع المصباح الكهربائي العملي؟",
        choices: ["توماس أديسون", "نيكولا تيسلا", "جراهام بيل", "آينشتاين"],
        answer: "توماس أديسون",
        hint: "💡 نور البيت",
        explanation: "توماس أديسون هو من أهدى العالم الضوء باختراعه للمصباح [76].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-019",
        type: "quiz",
        category: "geography",
        title: "🇦🇺 عاصمة أستراليا",
        description: "مدن عالمية",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 2,
        targetAgeGroup: "adult",
        question: "ما هي عاصمة دولة أستراليا الاتحادية؟",
        choices: ["كانبرا", "سيدني", "ملبورن", "بيرث"],
        answer: "كانبرا",
        hint: "🏙️ ليست سيدني",
        explanation: "كانبرا هي العاصمة السياسية لأستراليا رغم شهرة سيدني العالمية [14]، [56].",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-020",
        type: "quiz",
        category: "psychology",
        title: "✂️ نصل أوكام",
        description: "نماذج عقلية",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 4,
        targetAgeGroup: "adult",
        question: "ماذا يقترح نموذج 'نصل أوكام' عند وجود تفسيرين لظاهرة ما؟",
        choices: ["التفسير الأبسط هو الأرجح", "التفسير المعقد أفضل", "إهمال التفسيرين", "البحث عن ثالث"],
        answer: "التفسير الأبسط هو الأرجح",
        hint: "✂️ قاعدة البساطة",
        explanation: "يقترح هذا النموذج البدء بأبسط الافتراضات الممكنة واختبارها [77]، [78].",
        reward: { stars: 4, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-021",
        type: "quiz",
        category: "islamic",
        title: "🛡️ معركة حطين",
        description: "تحرير القدس",
        theme: "eid-al-adha",
        mood: "epic",
        difficulty: 2,
        targetAgeGroup: "adult",
        question: "من هو القائد المسلم الذي انتصر في معركة حطين؟",
        choices: ["صلاح الدين الأيوبي", "خالد بن الوليد", "عمر بن العاص", "سيف الدين قطز"],
        answer: "صلاح الدين الأيوبي",
        hint: "⚔️ بطل حطين",
        explanation: "فتح نصر حطين الطريق أمام صلاح الدين لاستعادة بيت المقدس [10]، [79].",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-022",
        type: "quiz",
        category: "science",
        title: "🩸 فصائل الدم",
        description: "حقائق طبية",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 2,
        targetAgeGroup: "adult",
        question: "كم عدد فصائل الدم الرئيسية لدى البشر؟",
        choices: ["8 فصائل", "4 فصائل", "10 فصائل", "فصيلتان"],
        answer: "8 فصائل",
        hint: "💉 تشمل الموجب والسالب",
        explanation: "يوجد 8 فصائل دم مختلفة يتم تصنيف البشر بناءً عليها [72].",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-023",
        type: "quiz",
        category: "geography",
        title: "📏 أطول دولة",
        description: "امتداد جغرافي فريد",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 2,
        targetAgeGroup: "adult",
        question: "ما هي الدولة الأطول في العالم من الشمال إلى الجنوب؟",
        choices: ["تشيلي", "روسيا", "البرازيل", "الأرجنتين"],
        answer: "تشيلي",
        hint: "🌎 أمريكا الجنوبية",
        explanation: "تمتد تشيلي بشكل طولي فريد بين المحيط وجبال الأنديز [53]، [56].",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-024",
        type: "quiz",
        category: "islamic",
        title: "📜 أول سفير",
        description: "دعاة الإسلام الأوائل",
        theme: "eid-al-adha",
        mood: "epic",
        difficulty: 3,
        targetAgeGroup: "adult",
        question: "من هو الصحابي الذي لُقب بأول سفير في الإسلام؟",
        choices: ["مصعب بن عمير", "عمر بن الخطاب", "زيد بن ثابت", "أبو بكر الصديق"],
        answer: "مصعب بن عمير",
        hint: "🕌 مبعوث المدينة",
        explanation: "أرسله النبي إلى المدينة ليعلم أهلها القرآن قبل الهجرة [27]، [80].",
        reward: { stars: 3, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-025",
        type: "quiz",
        category: "science",
        title: "💧 مادة الدماغ",
        description: "أهمية الترطيب",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 2,
        targetAgeGroup: "adult",
        question: "ما هي المادة التي تشكل نحو 80% من حجم الدماغ البشري؟",
        choices: ["الماء", "الدم", "الدهون", "الأكسجين"],
        answer: "الماء",
        hint: "🌊 سر الحياة",
        explanation: "يتكون الدماغ بنسبة كبيرة من الماء، لذا الجفاف يؤثر على التركيز [81]، [55].",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-026",
        type: "quiz",
        category: "geography",
        title: "⛰️ قمة العالم",
        description: "أعلى جبل",
        theme: "eid-al-adha",
        mood: "epic",
        difficulty: 1,
        targetAgeGroup: "adult",
        question: "ما هي أعلى قمة جبلية في العالم؟",
        choices: ["جبل إيفرست", "جبل كليمنجارو", "جبل السودة", "جبل جيس"],
        answer: "جبل إيفرست",
        hint: "🏔️ في الهملايا",
        explanation: "جبل إيفرست هو القمة الأعلى على مستوى سطح البحر عالمياً [55]، [68].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-027",
        type: "quiz",
        category: "islamic",
        title: "🛡️ معركة القادسية",
        description: "فتوحات العراق",
        theme: "eid-al-adha",
        mood: "epic",
        difficulty: 3,
        targetAgeGroup: "adult",
        question: "من كان قائد المسلمين في معركة القادسية الشهيرة؟",
        choices: ["سعد بن أبي وقاص", "خالد بن الوليد", "عمرو بن العاص", "أبو عبيدة الجراح"],
        answer: "سعد بن أبي وقاص",
        hint: "🏹 بطل القادسية",
        explanation: "قاد سعد بن أبي وقاص جيوش المسلمين للنصر في القادسية [66].",
        reward: { stars: 3, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-028",
        type: "quiz",
        category: "science",
        title: "🧪 الأنسولين",
        description: "هرمونات الجسم",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 2,
        targetAgeGroup: "adult",
        question: "أي عضو في جسم الإنسان هو المسؤول عن إنتاج الأنسولين؟",
        choices: ["البنكرياس", "الكبد", "الكلى", "المعدة"],
        answer: "البنكرياس",
        hint: "🧪 تنظيم السكر",
        explanation: "يقوم البنكرياس بإنتاج الأنسولين لتنظيم مستوى السكر في الدم [58]، [56].",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-029",
        type: "quiz",
        category: "geography",
        title: "🇩🇿 أكبر دولة عربية",
        description: "من حيث المساحة",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 1,
        targetAgeGroup: "adult",
        question: "ما هي أكبر دولة عربية من حيث المساحة حالياً؟",
        choices: ["الجزائر", "السعودية", "مصر", "السودان"],
        answer: "الجزائر",
        hint: "🇩🇿 في شمال أفريقيا",
        explanation: "أصبحت الجزائر هي الأكبر مساحة عربياً وأفريقياً بعد تقسيم السودان [53]، [82].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-030",
        type: "quiz",
        category: "psychology",
        title: "🧠 انحياز التوافر",
        description: "خداع العقل",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 4,
        targetAgeGroup: "adult",
        question: "ما هو 'انحياز التوافر' (Availability Bias) في اتخاذ القرارات؟",
        choices: ["الحكم بناءً على أحدث ما نتذكره", "تذكر الأشياء القديمة فقط", "توقع المستقبل دائماً", "حب المألوف"],
        answer: "الحكم بناءً على أحدث ما نتذكره",
        hint: "🧠 الذاكرة الحديثة",
        explanation: "يميل عقلنا للمبالغة في أهمية المعلومات التي نتذكرها بسهولة مؤخراً [83].",
        reward: { stars: 4, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-031",
        type: "quiz",
        category: "islamic",
        title: "🕋 الحجر الأسود",
        description: "عبادة حصرية",
        theme: "eid-al-adha",
        mood: "mystic",
        difficulty: 4,
        targetAgeGroup: "adult",
        question: "ما هي العبادة التي لا يفعلها في اللحظة نفسها إلا شخص واحد فقط في العالم؟",
        choices: ["تقبيل الحجر الأسود", "الصلاة", "الصيام", "قراءة الفاتحة"],
        answer: "تقبيل الحجر الأسود",
        hint: "🕋 في الكعبة",
        explanation: "بسبب ضيق المكان، لا يستطيع تقبيله فعلياً إلا شخص واحد في نفس الثانية [84]، [40].",
        reward: { stars: 4, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-032",
        type: "quiz",
        category: "science",
        title: "👂 أصغر عظمة",
        description: "في جسم الإنسان",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 3,
        targetAgeGroup: "adult",
        question: "أين تقع أصغر عظمة في جسم الإنسان (عظمة الركاب)؟",
        choices: ["في الأذن الوسطى", "في الأنف", "في إصبع القدم", "في اليد"],
        answer: "في الأذن الوسطى",
        hint: "👂 حاسة السمع",
        explanation: "عظمة الركاب الموجودة في الأذن هي الأصغر في هيكلنا العظمي [85]، [7].",
        reward: { stars: 3, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-033",
        type: "quiz",
        category: "geography",
        title: "🗺️ قناة السويس",
        description: "ممر عالمي",
        theme: "eid-al-adha",
        mood: "epic",
        difficulty: 1,
        targetAgeGroup: "adult",
        question: "ما هي القناة التي تربط بين البحر الأحمر والبحر المتوسط؟",
        choices: ["قناة السويس", "قناة بنما", "قناة كيل", "قناة كورنث"],
        answer: "قناة السويس",
        hint: "🇪🇬 في مصر",
        explanation: "قناة السويس هي أهم ممر ملاحي يربط الشرق بالغرب عبر مصر [48].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-034",
        type: "quiz",
        category: "islamic",
        title: "📜 نبي الخياطة",
        description: "مهن الأنبياء",
        theme: "eid-al-adha",
        mood: "peaceful",
        difficulty: 2,
        targetAgeGroup: "adult",
        question: "من هو النبي الذي كان يعمل في الخياطة ويسبح مع كل إبرة؟",
        choices: ["إدريس عليه السلام", "نوح عليه السلام", "داود عليه السلام", "صالح عليه السلام"],
        answer: "إدريس عليه السلام",
        hint: "🪡 أول من خط بالقلم",
        explanation: "سيدنا إدريس كان يعمل في الخياطة وكان دائم التسبيح [31].",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-035",
        type: "quiz",
        category: "science",
        title: "🍎 الجاذبية",
        description: "قوانين الطبيعة",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 1,
        targetAgeGroup: "adult",
        question: "من هو العالم الذي اكتشف قوانين الجاذبية والحركة؟",
        choices: ["إسحاق نيوتن", "جاليليو", "كابلر", "أرخميدس"],
        answer: "إسحاق نيوتن",
        hint: "🍎 التفاحة",
        explanation: "وضع نيوتن حجر الأساس للفيزياء باكتشاف الجاذبية [76].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-036",
        type: "quiz",
        category: "history",
        title: "🏛️ الأهرامات",
        description: "بناء خالد",
        theme: "eid-al-adha",
        mood: "epic",
        difficulty: 1,
        targetAgeGroup: "adult",
        question: "في أي بلد عربي تقع أهرامات الجيزة العظيمة؟",
        choices: ["مصر", "السودان", "الأردن", "العراق"],
        answer: "مصر",
        hint: "🇪🇬 أرض النيل",
        explanation: "بنيت الأهرامات في مصر القديمة كمعلم تاريخي عالمي [68].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-037",
        type: "quiz",
        category: "islamic",
        title: "📜 ليلة القدر",
        description: "ليلة مباركة",
        theme: "eid-al-adha",
        mood: "mystic",
        difficulty: 2,
        targetAgeGroup: "adult",
        question: "العبادة في 'ليلة القدر' خير من كم شهر؟",
        choices: ["1000 شهر", "100 شهر", "سنة واحدة", "10 سنوات"],
        answer: "1000 شهر",
        hint: "🌙 في رمضان",
        explanation: "قال تعالى: 'ليلة القدر خير من ألف شهر' لعظم أجرها [86].",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-038",
        type: "quiz",
        category: "science",
        title: "🔊 سرعة الصوت",
        description: "الصوت في الأوساط",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 4,
        targetAgeGroup: "adult",
        question: "أين ينتقل الصوت بسرعة أكبر؟",
        choices: ["في الماء", "في الهواء", "في الفراغ", "نفس السرعة"],
        answer: "في الماء",
        hint: "🌊 وسط كثيف",
        explanation: "ينتقل الصوت في الماء أسرع منه في الهواء بسبب تقارب الجزيئات [18].",
        reward: { stars: 4, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-039",
        type: "quiz",
        category: "geography",
        title: "🏔️ هضبة التبت",
        description: "تضاريس عملاقة",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 3,
        targetAgeGroup: "adult",
        question: "ما هو اللقب الجغرافي الذي يطلق على هضبة التبت؟",
        choices: ["سقف العالم", "أرض النار", "وادي النور", "هضبة الشمس"],
        answer: "سقف العالم",
        hint: "🏔️ أعلى هضبة",
        explanation: "تعتبر هضبة التبت هي الأعلى في العالم لذا تلقب بسقف العالم [55]، [81].",
        reward: { stars: 3, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-040",
        type: "quiz",
        category: "islamic",
        title: "🛡️ معركة أجنادين",
        description: "فتوحات الشام",
        theme: "eid-al-adha",
        mood: "epic",
        difficulty: 3,
        targetAgeGroup: "adult",
        question: "من القائد الذي حسم معركة أجنادين ضد الروم؟",
        choices: ["خالد بن الوليد", "عمرو بن العاص", "شرحبيل بن حسنة", "يزيد بن أبي سفيان"],
        answer: "خالد بن الوليد",
        hint: "⚔️ سيف الله",
        explanation: "قاد خالد بن الوليد جيوش المسلمين لنصر ساحق في أجنادين [79].",
        reward: { stars: 3, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-041",
        type: "quiz",
        category: "science",
        title: "🧠 ذاكرة السمك",
        description: "حقيقة أم أسطورة؟",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 4,
        targetAgeGroup: "adult",
        question: "ما هي المدة الحقيقية لذاكرة السمكة الذهبية؟",
        choices: ["أشهر وسنوات", "3 ثوانٍ", "يوم واحد", "ساعة واحدة"],
        answer: "أشهر وسنوات",
        hint: "🧠 ذاكرة قوية",
        explanation: "أثبتت الأبحاث أن ذاكرتها تمتد لأشهر ويمكن تدريبها أيضاً [87].",
        reward: { stars: 4, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-042",
        type: "quiz",
        category: "history",
        title: "🏛️ عجائب الدنيا",
        description: "حضارات قديمة",
        theme: "eid-al-adha",
        mood: "mystic",
        difficulty: 2,
        targetAgeGroup: "adult",
        question: "أين تقع 'الحدائق المعلقة' إحدى عجائب الدنيا السبع القديمة؟",
        choices: ["العراق", "مصر", "اليونان", "سوريا"],
        answer: "العراق",
        hint: "🇮🇶 في مدينة بابل",
        explanation: "بنيت الحدائق المعلقة في مدينة بابل التاريخية بالعراق [74]، [44].",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-043",
        type: "quiz",
        category: "islamic",
        title: "🕌 المسجد الأقصى",
        description: "أولى القبلتين",
        theme: "eid-al-adha",
        mood: "mystic",
        difficulty: 2,
        targetAgeGroup: "adult",
        question: "في أي دولة عربية يوجد المسجد الأقصى المبارك؟",
        choices: ["فلسطين", "الأردن", "السعودية", "مصر"],
        answer: "فلسطين",
        hint: "🇵🇸 القدس الشريف",
        explanation: "يقع المسجد الأقصى في مدينة القدس بدولة فلسطين [88].",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-044",
        type: "quiz",
        category: "science",
        title: "🌡️ غليان الماء",
        description: "درجات الحرارة",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 1,
        targetAgeGroup: "adult",
        question: "كم تبلغ درجة غليان الماء النقية تحت الضغط الجوي العادي؟",
        choices: ["100 درجة مئوية", "50 درجة مئوية", "0 درجة مئوية", "200 درجة مئوية"],
        answer: "100 درجة مئوية",
        hint: "🌡️ ماء ساخن جداً",
        explanation: "يغلي الماء ويتحول لبخار عند درجة 100 مئوية [89]، [7].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-045",
        type: "quiz",
        category: "psychology",
        title: "📱 إدمان الدوبامين",
        description: "سيكولوجية الهاتف",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 3,
        targetAgeGroup: "adult",
        question: "ما هو الهرمون المسؤول عن الشعور بالمكافأة عند وصول إشعار على هاتفك؟",
        choices: ["الدوبامين", "الأدرينالين", "الأنسولين", "الكورتيزول"],
        answer: "الدوبامين",
        hint: "🧠 ناقل عصبي",
        explanation: "تعتمد التطبيقات على تحفيز الدوبامين لإبقائك متصلاً لفترة أطول [90].",
        reward: { stars: 3, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-046",
        type: "quiz",
        category: "islamic",
        title: "📜 الصديق",
        description: "ألقاب الخلفاء الراشدين",
        theme: "eid-al-adha",
        mood: "warm",
        difficulty: 1,
        targetAgeGroup: "adult",
        question: "لماذا لُقب أبو بكر بـ 'الصديق'؟",
        choices: ["لأنه بادر بتصديق النبي", "لأنه كان تاجراً", "لأنه كان شجاعاً", "لأنه رفيقه في السفر"],
        answer: "لأنه بادر بتصديق النبي",
        hint: "🕌 حادثة الإسراء",
        explanation: "لُقب بذلك لأنه صدق النبي في كل خبر فور سماعه [35]، [91].",
        reward: { stars: 1, canUnlockTreasure: false },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-047",
        type: "quiz",
        category: "science",
        title: "🧬 كروية الدم",
        description: "دفاع الجسم",
        theme: "eid-al-adha",
        mood: "curious",
        difficulty: 2,
        targetAgeGroup: "adult",
        question: "ما هي كرات الدم المسؤولة عن الدفاع عن الجسم ضد الأمراض؟",
        choices: ["كريات الدم البيضاء", "كريات الدم الحمراء", "الصفائح الدموية", "البلازما"],
        answer: "كريات الدم البيضاء",
        hint: "🛡️ جيش الجسم",
        explanation: "تهاجم كريات الدم البيضاء الميكروبات لتحمينا من المرض [92].",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-048",
        type: "quiz",
        category: "geography",
        title: "🌊 أعمق نقطة",
        description: "تحت سطح البحر",
        theme: "eid-al-adha",
        mood: "mystic",
        difficulty: 4,
        targetAgeGroup: "adult",
        question: "ما هو اسم أعمق مكان معروف على سطح الأرض؟",
        choices: ["خندق ماريانا", "بئر كولا", "البحر الميت", "جراند كانيون"],
        answer: "خندق ماريانا",
        hint: "🌊 في المحيط الهادي",
        explanation: "خندق ماريانا هو أعمق نقطة في المحيطات بعمق 11 كم تقريباً [93].",
        reward: { stars: 4, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-049",
        type: "quiz",
        category: "history",
        title: "📜 أول عمل",
        description: "تاريخ الخلافة",
        theme: "eid-al-adha",
        mood: "epic",
        difficulty: 3,
        targetAgeGroup: "adult",
        question: "ما هو أول قرار اتخذه أبو بكر بعد توليه الخلافة؟",
        choices: ["إنفاذ جيش أسامة", "جمع القرآن", "قتال المرتدين", "بناء مسجد"],
        answer: "إنفاذ جيش أسامة",
        hint: "⚔️ وصية النبي",
        explanation: "أصر أبو بكر على تنفيذ وصية النبي بإنفاذ جيش أسامة [94].",
        reward: { stars: 3, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
    {
        id: "quiz-a-050",
        type: "quiz",
        category: "islamic",
        title: "🕋 الحج المبرور",
        description: "جزاء العبادة",
        theme: "eid-al-adha",
        mood: "peaceful",
        difficulty: 2,
        targetAgeGroup: "adult",
        question: "ما هو جزاء الحج المبرور كما ورد في الحديث؟",
        choices: ["الجنة", "زيادة المال", "القوة", "الشهرة"],
        answer: "الجنة",
        hint: "🌸 ليس له جزاء إلا..",
        explanation: "الحج المبرور يغفر الذنوب وجزاؤه الجنة عند الله [86].",
        reward: { stars: 2, canUnlockTreasure: true },
        tinyMissionPool: eidMissions,
    },
];